// Code generated by Slice Machine. DO NOT EDIT.

import About from './About';
import BannerSectionMiddleContent from './BannerSectionMiddleContent';
import BannerSectionSideContent from './BannerSectionSideContent';
import CallToAction from './CallToAction';
import CardsSection from './CardsSection';
import Certification from './Certification';
import Footer from './Footer';
import GridSection from './GridSection';
import HeroSection from './HeroSection';
import Main from './Main';
import NavigationItems from './NavigationItems';
import News from './News';
import TeamDropdown from './TeamDropdown';
import TeamProfile from './TeamProfile';
import TopNav from './TopNav';

export {
	About,
	BannerSectionMiddleContent,
	BannerSectionSideContent,
	CallToAction,
	CardsSection,
	Certification,
	Footer,
	GridSection,
	HeroSection,
	Main,
	NavigationItems,
	News,
	TeamDropdown,
	TeamProfile,
	TopNav,
};

export const components = {
	about: About,
	banner_with_middle_content: BannerSectionMiddleContent,
	banner_section_side_content: BannerSectionSideContent,
	call_to_action: CallToAction,
	cards_section: CardsSection,
	certification: Certification,
	footer: Footer,
	grid_section: GridSection,
	hero_section: HeroSection,
	main: Main,
	navigation_items: NavigationItems,
	news: News,
	team_dropdown: TeamDropdown,
	team_profile: TeamProfile,
	top_nav: TopNav,
};
