// Code generated by Slice Machine. DO NOT EDIT.

import About from './About';
import CallToAction from './CallToAction';
import Certification from './Certification';
import Footer from './Footer';
import Header from './Header';
import HeroSection from './HeroSection';
import News from './News';
import TeamDropdown from './TeamDropdown';
import TeamProfile from './TeamProfile';
import TopNav from './TopNav';

export {
	About,
	CallToAction,
	Certification,
	Footer,
	Header,
	HeroSection,
	News,
	TeamDropdown,
	TeamProfile,
	TopNav,
};

export const components = {
	about: About,
	call_to_action: CallToAction,
	certification: Certification,
	footer: Footer,
	header: Header,
	hero_section: HeroSection,
	news: News,
	team_dropdown: TeamDropdown,
	team_profile: TeamProfile,
	top_nav: TopNav,
};
